# Generated by Django 3.2.4 on 2023-02-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='product',
            field=models.ManyToManyField(null=True, to='cartapp.UserCartProduct'),
        ),
    ]
