# Generated by Django 3.2.4 on 2023-02-27 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0002_auto_20230227_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercartproduct',
            name='owner',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='cartapp.user'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
